# Generated by Django 4.1.2 on 2022-10-24 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='Наименование груза')),
                ('gross_weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='Вес брутто')),
                ('count_seats', models.IntegerField(default=0, verbose_name='Колличество мест')),
                ('length_seats', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='Длина')),
                ('width_seats', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='Ширина')),
                ('height_seats', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='Высота')),
                ('type_seats', models.CharField(choices=[(None, 'Выбрать'), ('1', 'Паллеты'), ('2', 'Ящики'), ('3', 'Рулоны'), ('4', 'Навал'), ('6', 'Коробки'), ('6', 'Другое')], max_length=1, verbose_name='Вид мест')),
                ('point_departure', models.CharField(max_length=100, verbose_name='Пункт отправления')),
                ('destination', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryClaim',
            fields=[
                ('claim_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.claim')),
                ('start_date', models.DateField(verbose_name='с')),
                ('end_date', models.DateField(verbose_name='по')),
                ('fly', models.BooleanField(default=False, verbose_name='Авиа')),
                ('train', models.BooleanField(default=False, verbose_name='Ж/д')),
                ('ship', models.BooleanField(default=False, verbose_name='Море')),
                ('auto', models.BooleanField(default=False, verbose_name='Авто')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('messenger', models.CharField(blank=True, choices=[(None, 'Выбрать'), ('WTA', 'WhatsApp'), ('VB', 'Viber'), ('TG', 'Telegram')], max_length=3, verbose_name='Messenger')),
                ('messenger_number', models.CharField(blank=True, max_length=30, verbose_name='Номер мессенджера')),
            ],
            options={
                'verbose_name': 'Предварительная заявка',
                'verbose_name_plural': 'Предварительные заявки',
            },
            bases=('claims.claim',),
        ),
        migrations.CreateModel(
            name='ShippingClaim',
            fields=[
                ('claim_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='claims.claim')),
                ('code', models.IntegerField(verbose_name='Код ТНВЭД')),
                ('cargo_features', models.CharField(choices=[(None, 'Выбрать'), ('D', 'Опасный'), ('ND', 'Не опасный')], max_length=2, verbose_name='Особеннонсти груза')),
                ('date_loading', models.DateField(verbose_name='Дата Загрузки')),
                ('transport', models.CharField(choices=[(None, 'Выбрать'), ('FLY', 'Авиа'), ('TRAIN', 'Ж/д'), ('SHIP', 'Море'), ('AUTO', 'Авто')], max_length=5, verbose_name='Вид транспорта')),
                ('person_loading', models.CharField(max_length=100, verbose_name='Контактное лицо на загрузке')),
                ('per_load_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('per_load_msg', models.CharField(blank=True, choices=[(None, 'Выбрать'), ('WTA', 'WhatsApp'), ('VB', 'Viber'), ('TG', 'Telegram')], max_length=3, verbose_name='Messenger')),
                ('per_load_msg_number', models.CharField(blank=True, max_length=30, verbose_name='Номер мессенджера')),
                ('person_unloading', models.CharField(max_length=100, verbose_name='Контактное лицо на выгрузке')),
                ('per_unload_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('per_unload_msg', models.CharField(blank=True, choices=[(None, 'Выбрать'), ('WTA', 'WhatsApp'), ('VB', 'Viber'), ('TG', 'Telegram')], max_length=3, verbose_name='Messenger')),
                ('per_unload_msg_number', models.CharField(blank=True, max_length=30, verbose_name='Номер мессенджера')),
            ],
            options={
                'verbose_name': 'Заявка на перевозку',
                'verbose_name_plural': 'Заявки на перевозку',
            },
            bases=('claims.claim',),
        ),
    ]
