# Generated by Django 4.1.2 on 2022-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingclaim',
            name='cargo_features',
            field=models.CharField(choices=[('D', 'Опасный'), ('ND', 'Не опасный')], max_length=2, verbose_name='Особеннонсти груза'),
        ),
        migrations.AlterField(
            model_name='shippingclaim',
            name='code',
            field=models.IntegerField(verbose_name='Код ТН ВЭД'),
        ),
    ]
