# Generated by Django 4.2.1 on 2023-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='count_seats',
            field=models.IntegerField(blank=True, verbose_name='Колличество мест'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='Вес брутто'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='height_seats',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='length_seats',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type_seats',
            field=models.CharField(blank=True, choices=[(None, 'Выбрать'), ('1', 'Паллеты'), ('2', 'Ящики'), ('3', 'Рулоны'), ('4', 'Навал'), ('6', 'Коробки'), ('6', 'Другое')], max_length=1, verbose_name='Вид мест'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='width_seats',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='preliminaryclaim',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='preliminaryclaim',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='с'),
        ),
    ]
