# Generated by Django 4.1.2 on 2022-10-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_shippingclaim_cargo_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingclaim',
            name='cargo_features',
            field=models.CharField(choices=[(None, None), ('D', 'Опасный'), ('ND', 'Не опасный')], max_length=2, verbose_name='Особеннонсти груза'),
        ),
    ]
