# Generated by Django 4.1.2 on 2022-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_shippingclaim_cargo_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingclaim',
            name='cargo_features',
            field=models.CharField(choices=[('D', 'Опасный'), ('ND', 'Не опасный')], max_length=2, verbose_name='Особеннонсти груза'),
        ),
    ]
