# Generated by Django 4.1.2 on 2022-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_shippingclaim_cargo_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingclaim',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Код ТН ВЭД'),
        ),
    ]
