# Generated by Django 4.1.2 on 2022-10-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_shippingclaim_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingclaim',
            name='cargo_insurance',
            field=models.CharField(choices=[('YES', 'Требуется'), ('NO', 'Не требуется')], default='NO', max_length=3, verbose_name='Страхование граза'),
        ),
        migrations.AlterField(
            model_name='shippingclaim',
            name='cargo_features',
            field=models.CharField(choices=[('D', 'Опасный'), ('ND', 'Не опасный')], default='ND', max_length=2, verbose_name='Особеннонсти груза'),
        ),
    ]
